// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getCumsumCpp
inline arma::mat getCumsumCpp(const arma::mat& X);
RcppExport SEXP _R6demo_getCumsumCpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(getCumsumCpp(X));
    return rcpp_result_gen;
END_RCPP
}
// createCostObj
SEXP createCostObj(const arma::mat& X);
RcppExport SEXP _R6demo_createCostObj(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(createCostObj(X));
    return rcpp_result_gen;
END_RCPP
}
// binSegCpp
List binSegCpp(Rcpp::XPtr<Cost> Xptr, const int& maxNRegimes);
RcppExport SEXP _R6demo_binSegCpp(SEXP XptrSEXP, SEXP maxNRegimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Cost> >::type Xptr(XptrSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxNRegimes(maxNRegimesSEXP);
    rcpp_result_gen = Rcpp::wrap(binSegCpp(Xptr, maxNRegimes));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_costModule();

static const R_CallMethodDef CallEntries[] = {
    {"_R6demo_getCumsumCpp", (DL_FUNC) &_R6demo_getCumsumCpp, 1},
    {"_R6demo_createCostObj", (DL_FUNC) &_R6demo_createCostObj, 1},
    {"_R6demo_binSegCpp", (DL_FUNC) &_R6demo_binSegCpp, 2},
    {"_rcpp_module_boot_costModule", (DL_FUNC) &_rcpp_module_boot_costModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_R6demo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
