# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slowBinSegCpp <- function(tsMat, maxNRegimes) {
    .Call(`_R6demo_slowBinSegCpp`, tsMat, maxNRegimes)
}

fastBinSegCpp <- function(tsMat, maxNRegimes) {
    .Call(`_R6demo_fastBinSegCpp`, tsMat, maxNRegimes)
}

