# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCumsumCpp <- function(X) {
    .Call(`_R6demo_getCumsumCpp`, X)
}

createCostObj <- function(X) {
    .Call(`_R6demo_createCostObj`, X)
}

binSegCpp <- function(Xptr, maxNRegimes) {
    .Call(`_R6demo_binSegCpp`, Xptr, maxNRegimes)
}

